-- 코드를 작성해주세요
-- PARENT_ITEM_ID 에 없는 거 추출
SELECT i.ITEM_ID, i.ITEM_NAME, i.RARITY FROM ITEM_INFO i
LEFT JOIN ITEM_TREE t ON i.ITEM_ID = t.PARENT_ITEM_ID
WHERE t.ITEM_ID IS NULL
ORDER BY i.ITEM_ID DESC