-- 코드를 입력하세요
SELECT DISTINCT USER_ID, PRODUCT_ID FROM ONLINE_SALE o1 WHERE EXISTS(
    SELECT 1 FROM ONLINE_SALE o2 WHERE o1.ONLINE_SALE_ID != o2.ONLINE_SALE_ID AND o1.USER_ID = o2.USER_ID AND o1.PRODUCT_ID = o2.PRODUCT_ID
) ORDER BY USER_ID, PRODUCT_ID DESC;