-- 코드를 입력하세요
SELECT i.FOOD_TYPE, i.REST_ID, i.REST_NAME, i.FAVORITES FROM REST_INFO i
WHERE (i.FOOD_TYPE, i.FAVORITES) IN (
    SELECT FOOD_TYPE, MAX(FAVORITES)
    FROM REST_INFO
    WHERE i.FOOD_TYPE = FOOD_TYPE
)
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC