-- 코드를 작성해주세요
SELECT i1.ITEM_ID, i1.ITEM_NAME, i1.RARITY FROM ITEM_TREE t
LEFT JOIN ITEM_INFO i1 ON i1.ITEM_ID = t.ITEM_ID -- 진화
LEFT JOIN ITEM_INFO i2 ON i2.ITEM_ID = t.PARENT_ITEM_ID -- 원래
WHERE i2.RARITY = 'RARE'
ORDER BY i1.ITEM_ID DESC