SELECT ID, FISH_NAME, LENGTH FROM (
    SELECT ID, FISH_NAME, LENGTH, i.FISH_TYPE FROM FISH_INFO i
    LEFT JOIN FISH_NAME_INFO n ON n.FISH_TYPE = i.FISH_TYPE
) f1
WHERE (f1.FISH_TYPE, f1.LENGTH) IN (
  SELECT f2.FISH_TYPE, MAX(f2.LENGTH) AS LENGTH FROM FISH_INFO f2
  GROUP BY FISH_TYPE
)
ORDER BY ID