-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', b.BOARD_ID, '/', f.FILE_ID, f.FILE_NAME, f.FILE_EXT) AS FILE_PATH FROM (
  SELECT * FROM USED_GOODS_BOARD b
  WHERE b.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
) AS b
LEFT JOIN USED_GOODS_FILE f ON b.BOARD_ID = f.BOARD_ID